apiVersion: apps/v1
kind: Deployment
metadata:
  name: workstream-api-good
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workstream-api
  template:
    metadata:
      labels:
        app: workstream-api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: api
          image: workstream-api:hardened
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
